### ISSUE TITLE
has bug：/mw suffer Constantly reset the character position

### ISSUE THREAD

**Issue by yehuoshun** [NotThorny/MobWave#6]
I remember wrong, not /mw stop,is /mw suffer

**Comment by yehuoshun** [comment]
![video](https://github.com/yehuoshun/Cartographic_bed_public/blob/main/video/20221109184756.webm)

**Comment by yehuoshun** [comment]
20:44:37 <WARN:SceneMeta> No script found for scene 50099

**Comment by yehuoshun** [comment]
scene not found?
Is this the cause of the bug？

**Comment by NotThorny** [comment]
/mw suffer intentionally teleports you around to make it more difficult (and suffer-esque)
Scene script you can ignore, it's not an issue with the plugin and won't cause problems.
